name: Code formatting check
on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Run black
        uses: psf/black@stable
